(deftheme zenburn-my
  "Created 2020-10-15.")

(custom-theme-set-variables
 'zenburn-my
 '(ansi-color-names-vector ["#3F3F3F" "#CC9393" "#7F9F7F" "#F0DFAF" "#8CD0D3" "#DC8CC3" "#93E0E3" "#DCDCCC"]))

(custom-theme-set-faces
 'zenburn-my
 '(button ((t (:underline t))))
 '(link ((t (:foreground "#F0DFAF" :underline t :weight bold))))
 '(link-visited ((t (:foreground "#D0BF8F" :underline t :weight normal))))
 '(cursor ((t (:foreground "#DCDCCC" :background "#FFFFEF"))))
 '(widget-field ((t (:foreground "#DCDCCC" :background "#6F6F6F"))))
 '(escape-glyph ((t (:foreground "#F0DFAF" :weight bold))))
 '(fringe ((t (:foreground "#DCDCCC" :background "#4F4F4F"))))
 '(header-line ((t (:foreground "#F0DFAF" :background "#2B2B2B" :box (:line-width -1 :style released-button)))))
 '(highlight ((t (:background "#383838"))))
 '(success ((t (:foreground "#7F9F7F" :weight bold))))
 '(warning ((t (:foreground "#DFAF8F" :weight bold))))
 '(tooltip ((t (:foreground "#DCDCCC" :background "#4F4F4F"))))
 '(completions-annotations ((t (:foreground "#656555"))))
 '(match ((t (:background "#2B2B2B" :foreground "#DFAF8F" :weight bold))))
 '(isearch ((t (:foreground "#D0BF8F" :weight bold :background "#5F5F5F"))))
 '(isearch-fail ((t (:foreground "#DCDCCC" :background "#8C5353"))))
 '(lazy-highlight ((t (:background "#5F5F5F" :foreground "#D0BF8F" :weight bold))))
 '(menu ((t (:foreground "#DCDCCC" :background "#3F3F3F"))))
 '(minibuffer-prompt ((t (:foreground "#F0DFAF"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#8FB28F" :background "#2B2B2B" :box (:line-width -1 :style released-button))) (t :inverse-video t)))
 '(mode-line-buffer-id ((t (:foreground "#F0DFAF" :weight bold))))
 '(mode-line-inactive ((t (:foreground "#5F7F5F" :background "#383838" :box (:line-width -1 :style released-button)))))
 '(region ((((class color) (min-colors 89)) (:background "#2B2B2B")) (t :inverse-video t)))
 '(secondary-selection ((t (:background "#5F5F5F"))))
 '(trailing-whitespace ((t (:background "#CC9393"))))
 '(vertical-border ((t (:foreground "#DCDCCC"))))
 '(font-lock-builtin-face ((t (:foreground "#DCDCCC" :weight bold))))
 '(font-lock-comment-face ((t (:foreground "#7F9F7F"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#5F7F5F"))))
 '(font-lock-constant-face ((t (:foreground "#BFEBBF"))))
 '(font-lock-doc-face ((t (:foreground "#9FC59F"))))
 '(font-lock-function-name-face ((t (:foreground "#93E0E3"))))
 '(font-lock-keyword-face ((t (:foreground "#F0DFAF" :weight bold))))
 '(font-lock-negation-char-face ((t (:foreground "#F0DFAF" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#94BFF3"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#F0DFAF" :weight bold))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#7F9F7F" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#CC9393"))))
 '(font-lock-type-face ((t (:foreground "#7CB8BB"))))
 '(font-lock-variable-name-face ((t (:foreground "#DFAF8F"))))
 '(font-lock-warning-face ((t (:foreground "#D0BF8F" :weight bold))))
 '(line-number ((t (:foreground "#6F6F6F" :background "#383838"))))
 '(line-number-current-line ((t (:inherit line-number :foreground "#D0BF8F"))))
 '(diff-added ((t (:background "#2F4F2F" :foreground "#9FC59F"))))
 '(diff-changed ((t (:background "#555511" :foreground "#E0CF9F"))))
 '(diff-removed ((t (:background "#6C3333" :foreground "#DCA3A3"))))
 '(diff-refine-added ((t (:background "#3F5F3F" :foreground "#AFD8AF"))))
 '(diff-refine-changed ((t (:background "#888811" :foreground "#F0DFAF"))))
 '(diff-refine-removed ((t (:background "#7C4343" :foreground "#ECB3B3"))))
 '(diff-header ((((class color) (min-colors 89)) (:background "#5F5F5F")) (t (:background "#DCDCCC" :foreground "#3F3F3F"))))
 '(diff-file-header ((((class color) (min-colors 89)) (:background "#5F5F5F" :foreground "#DCDCCC" :weight bold)) (t (:background "#DCDCCC" :foreground "#3F3F3F" :weight bold))))
 '(gnus-group-mail-1 ((t (:weight bold :inherit gnus-group-mail-1-empty))))
 '(gnus-group-mail-1-empty ((t (:inherit gnus-group-news-1-empty))))
 '(gnus-group-mail-2 ((t (:weight bold :inherit gnus-group-mail-2-empty))))
 '(gnus-group-mail-2-empty ((t (:inherit gnus-group-news-2-empty))))
 '(gnus-group-mail-3 ((t (:weight bold :inherit gnus-group-mail-3-empty))))
 '(gnus-group-mail-3-empty ((t (:inherit gnus-group-news-3-empty))))
 '(gnus-group-mail-low ((t (:weight bold :inherit gnus-group-mail-low-empty))))
 '(gnus-group-mail-low-empty ((t (:inherit gnus-group-news-low-empty))))
 '(gnus-group-news-1 ((t (:weight bold :inherit gnus-group-news-1-empty))))
 '(gnus-group-news-2 ((t (:weight bold :inherit gnus-group-news-2-empty))))
 '(gnus-group-news-3 ((t (:weight bold :inherit gnus-group-news-3-empty))))
 '(gnus-group-news-4 ((t (:weight bold :inherit gnus-group-news-4-empty))))
 '(gnus-group-news-5 ((t (:weight bold :inherit gnus-group-news-5-empty))))
 '(gnus-group-news-6 ((t (:weight bold :inherit gnus-group-news-6-empty))))
 '(gnus-group-news-low ((t (:weight bold :inherit gnus-group-news-low-empty))))
 '(gnus-summary-cancelled ((t (:foreground "#DFAF8F"))))
 '(gnus-summary-high-ancient ((t (:foreground "#8CD0D3"))))
 '(gnus-summary-high-read ((t (:foreground "#7F9F7F" :weight bold))))
 '(gnus-summary-high-ticked ((t (:foreground "#DFAF8F" :weight bold))))
 '(gnus-summary-high-unread ((t (:foreground "#DCDCCC" :weight bold))))
 '(gnus-summary-low-ancient ((t (:foreground "#8CD0D3"))))
 '(gnus-summary-low-read ((t (:foreground "#7F9F7F"))))
 '(gnus-summary-low-ticked ((t (:foreground "#DFAF8F" :weight bold))))
 '(gnus-summary-low-unread ((t (:foreground "#DCDCCC"))))
 '(gnus-summary-normal-ancient ((t (:foreground "#8CD0D3"))))
 '(gnus-summary-normal-read ((t (:foreground "#7F9F7F"))))
 '(gnus-summary-normal-ticked ((t (:foreground "#DFAF8F" :weight bold))))
 '(gnus-summary-normal-unread ((t (:foreground "#DCDCCC"))))
 '(gnus-summary-selected ((t (:foreground "#F0DFAF" :weight bold))))
 '(gnus-group-news-1-empty ((t (:foreground "#F0DFAF"))))
 '(gnus-group-news-2-empty ((t (:foreground "#AFD8AF"))))
 '(gnus-group-news-3-empty ((t (:foreground "#8FB28F"))))
 '(gnus-group-news-4-empty ((t (:foreground "#6CA0A3"))))
 '(gnus-group-news-5-empty ((t (:foreground "#5C888B"))))
 '(gnus-group-news-6-empty ((t (:foreground "#5F5F5F"))))
 '(gnus-group-news-low-empty ((t (:foreground "#5F5F5F"))))
 '(message-cited-text-1 ((t (:inherit font-lock-comment-face))))
 '(message-header-name ((t (:foreground "#8FB28F"))))
 '(message-header-other ((t (:foreground "#7F9F7F"))))
 '(message-header-to ((t (:foreground "#F0DFAF" :weight bold))))
 '(message-header-cc ((t (:foreground "#F0DFAF" :weight bold))))
 '(message-header-newsgroups ((t (:foreground "#F0DFAF" :weight bold))))
 '(message-header-subject ((t (:foreground "#DFAF8F" :weight bold))))
 '(message-header-xheader ((t (:foreground "#7F9F7F"))))
 '(message-mml ((t (:foreground "#F0DFAF" :weight bold))))
 '(message-separator ((t (:inherit font-lock-comment-face))))
 '(org-agenda-date-today ((t (:foreground "#FFFFEF" :slant italic :weight bold))))
 '(org-agenda-structure ((t (:inherit font-lock-comment-face))))
 '(org-archived ((t (:foreground "#DCDCCC" :weight bold))))
 '(org-checkbox ((t (:background "#5F5F5F" :foreground "#FFFFEF" :box (:line-width 1 :style released-button)))))
 '(org-date ((t (:foreground "#8CD0D3" :underline t))))
 '(org-done ((t (:weight bold :weight bold :foreground "#AFD8AF"))))
 '(org-formula ((t (:foreground "#D0BF8F"))))
 '(org-headline-done ((t (:foreground "#AFD8AF"))))
 '(org-hide ((t (:foreground "#3F3F3F"))))
 '(org-level-1 ((t (:inherit default :foreground "#DFAF8F"))))
 '(org-level-2 ((t (:inherit default :foreground "#BFEBBF"))))
 '(org-level-3 ((t (:inherit default :foreground "#7CB8BB"))))
 '(org-level-4 ((t (:inherit default :foreground "#D0BF8F"))))
 '(org-level-5 ((t (:inherit default :foreground "#93E0E3"))))
 '(org-level-6 ((t (:inherit default :foreground "#9FC59F"))))
 '(org-level-7 ((t (:inherit default :foreground "#8C5353"))))
 '(org-level-8 ((t (:inherit default :foreground "#4C7073"))))
 '(org-link ((t (:foreground "#D0BF8F" :underline t))))
 '(org-scheduled ((t (:foreground "#BFEBBF"))))
 '(org-scheduled-previously ((t (:foreground "#CC9393"))))
 '(org-scheduled-today ((t (:foreground "#94BFF3"))))
 '(org-sexp-date ((t (:foreground "#94BFF3" :underline t))))
 '(org-special-keyword ((t (:inherit font-lock-comment-face))))
 '(org-table ((t (:foreground "#9FC59F"))))
 '(org-tag ((t (:weight bold :weight bold))))
 '(org-time-grid ((t (:foreground "#DFAF8F"))))
 '(org-todo ((t (:weight bold :foreground "#CC9393" :weight bold))))
 '(org-upcoming-deadline ((t (:inherit font-lock-keyword-face))))
 '(org-warning ((t (:weight bold :foreground "#CC9393" :weight bold :underline nil))))
 '(org-column ((t (:background "#2B2B2B"))))
 '(org-column-title ((t (:background "#2B2B2B" :underline t :weight bold))))
 '(org-mode-line-clock ((t (:foreground "#DCDCCC" :background "#2B2B2B"))))
 '(org-mode-line-clock-overrun ((t (:foreground "#3F3F3F" :background "#BC8383"))))
 '(org-ellipsis ((t (:foreground "#E0CF9F" :underline t))))
 '(org-footnote ((t (:foreground "#93E0E3" :underline t))))
 '(org-document-title ((t (:inherit default :foreground "#8CD0D3" :weight bold :height 1.3))))
 '(org-document-info ((t (:foreground "#8CD0D3"))))
 '(outline-1 ((t (:inherit default :foreground "#DFAF8F"))))
 '(outline-2 ((t (:inherit default :foreground "#BFEBBF"))))
 '(outline-3 ((t (:inherit default :foreground "#7CB8BB"))))
 '(outline-4 ((t (:inherit default :foreground "#D0BF8F"))))
 '(outline-5 ((t (:inherit default :foreground "#93E0E3"))))
 '(outline-6 ((t (:inherit default :foreground "#9FC59F"))))
 '(outline-7 ((t (:inherit default :foreground "#8C5353"))))
 '(outline-8 ((t (:inherit default :foreground "#4C7073"))))
 '(show-paren-mismatch ((t (:foreground "#DCA3A3" :background "#6F6F6F" :weight bold))))
 '(show-paren-match ((t (:foreground "#DCDCCC" :background "#6F6F6F" :weight bold))))
 '(default ((t (:foreground "#DCDCCC" :background "#3F3F3F")))))

(provide-theme 'zenburn-my)
