theme = "papercolor-dark"

[editor]
bufferline = "always"
auto-format = false # disable auto-formatting on save

[editor.statusline]
right = ["diagnostics", "selections", "register", "position", "total-line-numbers", "file-encoding"]

[editor.gutters]
layout = ["diagnostics", "line-numbers", "diff"]

[editor.soft-wrap]
enable = true
wrap-indicator = ""
max-indent-retain = 0
max-wrap = 0

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[keys.normal]
C-c = "no_op"

[keys.insert]
C-c = "normal_mode"

[keys.select]
C-c = "normal_mode"
